	  <p>
	    Welcome to the Flippers Server Administration Page.
	  </p>
	  <p>
	    Across the top of this page are the top level options;
	    <% if data["user.admin"] %>
	      Ports, Applications, Users, 
	    <% endif %>
	    Servers, Statistics, Preferences and Logout.
	  </p>
	  <p>
	    Latest news from the <a href="http://hww3.riverweb.com/exec/category/Fins">Fins Developer Blog</a>:
	  </p>
