<%@include file="top.phtml" %>
	  <p class="header">
	    Welcome to Flippers.
	  </p>
	  <p>
	    Please log in.
	  </p>
	  <table id="login_options">
	    <form method="post" action="/login">
	    <tr>
	      <td>
		<label for="username">User name</label>
	      </td>
	      <td>
		<input id="username" name="username" type="text" size="16" />
	      </td>
	    </tr>
	    <tr>
	      <td>
		<label for="password">Password</label>
	      </td>
	      <td>
		<input id="password" name="password" type="password" size="16" />
	      </td>
	    </tr>
	    <tr>
	      <td colspan="2">
		<button id="login_go" type="submit">log in</button>
	      </td>
	      <tr>
		<td id="flash" class="warning" colspan="2">
		  <% if data["flash"] %>
		    <%$flash%>
		  <% endif %>
		</td>
	      </tr>
	    </tr>
	    </form>
	  </table>
<%@include file="bottom.phtml" %>
