<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3c.org/1999/xhtml" xml:lang="en">
  <head>
    <title><%$page.title%></title>
    <link rel="stylesheet" type="text/css" href="/static/css/flippers.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/<%$page.name%>.css" />
    <script type="text/javascript" src="/static/js/dojo/dojo.js"></script>
    <script type="text/javascript" src="/static/js/flippers.js"></script>
    <script type="text/javascript" src="/static/js/<%$page.name%>.js"></script>
  </head>
  <body>
    <div>
      <div id="box">
	<div id="imgcontainer">
	  <img id="Fins_250v" src="/static/images/Fins_250v.jpg" />
	</div>
	<div>
